ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/charger_policy/rainbow/include
obj-$(CONFIG_BQ_FUEL_GAUGE)				+= bq28z610.o
obj-$(CONFIG_HUAQIN_FUEL_ALGORITHM)                     += hq_fuel_algorithm.o
