# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_CHARGEPUMP_SOUTHCHIP)              += southchip/
obj-$(CONFIG_CHARGEPUMP_NUVOLTA)                += nuvolta/
obj-$(CONFIG_CHARGEPUMP_TI)                     += ti/
