#
# Makefile for hl5281 or dio4485 type-c switch driver
#
obj-m += typec_switch.o

subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/power_throttling
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/pbm
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/
subdir-ccflags-y += -I$(srctree)/sound/soc/codecs/
