# Makefile for the focaltech touchscreen drivers.
obj-m += ft8722.o
ft8722-y	+= focaltech_core.o \
		focaltech_ex_fun.o \
		focaltech_ex_mode.o \
		focaltech_gesture.o \
		focaltech_esdcheck.o \
		focaltech_point_report_check.o \
		focaltech_test.o \
		focaltech_test_ini.o \
		focaltech_test_ft8722.o \
		focaltech_flash.o \
		focaltech_spi.o


