# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_FUEL_GAUGE_BQ27Z561)	+= bq27z561_drv.o
bq27z561_drv-objs := bq27z561.o

obj-$(CONFIG_HQ_CHARGER_MANAGER)	+= hq_chg.o
obj-$(CONFIG_HQ_CHARGER_MANAGER)	+= sy6970_charger.o
hq_chg-objs	:= hq_chg_new.o hq_chg_cust.o hq_voter.o
#hq_chg-objs	:= hq_chg.o