# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
# P6 code for HQFEAT-123538 by p-gaobowei1 at 2025/06/11 start
obj-$(CONFIG_POWER_BYP)	+= byp/
# P6 code for HQFEAT-123538 by p-gaobowei1 at 2025/06/11 end
