# SPDX-License-Identifier: GPL-2.0

subdir-ccflags-y += -I$(srctree)/drivers/misc/hq_typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/common/include

obj-$(CONFIG_TCPC_CLASS) += tcpc/