# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/charger_class/include

obj-$(CONFIG_HQ_ADAPTER_CLASS)        += hq_adapter_class.o
obj-$(CONFIG_HQ_CHARGER_CLASS)        += hq_charger_class.o
obj-$(CONFIG_HQ_FG_CLASS)             += hq_fg_class.o
obj-$(CONFIG_HQ_CP_CLASS)             += hq_cp_class.o
obj-$(CONFIG_HQ_LED_CLASS)            += hq_led_class.o
obj-$(CONFIG_XM_ADAPTER_CLASS)        += xm_adapter_class.o
