# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-y += -I$(srctree)/arch/arm64/boot/dts/mediatek/hq_chg
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/charger_class/include
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/chargepump/nuvolta/include

obj-$(CONFIG_NU_CHARGEPUMP_NU2115)    += nu2115.o
