# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/$(BUILD_TARGET_PRODUCT)/tcpc/inc
ccflags-y += -I$(srctree)/drivers/power/supply-$(BUILD_TARGET_PRODUCT)

obj-$(CONFIG_EXTCON_MTK_USB) += extcon-mtk-usb.o
