# SPDX-License-Identifier: GPL-2.0
subdir-ccflags-y += -I$(srctree)/arch/arm64/boot/dts/mediatek/hq_chg
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/charger_class/include
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/hq_chg/common/include

obj-$(CONFIG_SC_CHARGEPUMP_SC8541)    += sc8541.o
