MODULE_NAME := uft-pcie-boot
obj-$(CONFIG_UFT_PCIE_BOOT) += $(MODULE_NAME).o
$(MODULE_NAME)-objs += uft_pcie_boot.o
$(MODULE_NAME)-objs += uft_pcie_ep.o
$(MODULE_NAME)-objs += uft_pcie_debugfs.o
$(MODULE_NAME)-objs += xring_pcie_hdma.o

ccflags-y += -I$(KERNEL_SRC)/drivers/pci/controller/dwc