# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SUBPMIC_SOUTHCHIP)              += southchip/
obj-$(CONFIG_SUBPMIC_NUVOLTA)                += nuvolta/
obj-$(CONFIG_SUBPMIC_SILERGY)                += silergy/
