# SPDX-License-Identifier: GPL-2.0

# Franklin basic
dtb-y += soc/xring_o1_basic.dtb

# ASIC Overlay Resurce
dtb-y += overlay/udp/udp_phone/franklin1_udp_phone_overlay.dtbo
dtb-y += overlay/udp/udp_pad/franklin1_udp_pad_overlay.dtbo
dtb-y += overlay/product/phone/phone_o2s/franklin1_o2s_phone_overlay.dtbo
dtb-y += overlay/product/pad/pad_o80/franklin1_o80_pad_overlay.dtbo
dtb-y += overlay/product/pad/pad_o81a/franklin1_o81a_pad_overlay.dtbo

