name: KSU Build with AnyKernel3
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt update && sudo apt install -y git make bc wget zip
    - name: Get KSU
      run: git clone --depth=1 https://github.com/KernelSU-Next/KernelSU-Next.git
    - name: Build
      run: |
        export ARCH=arm64
        make creek_GKI-config
        make -j2
    - name: AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp arch/arm64/boot/Image.gz AnyKernel3/
        cd AnyKernel3 && zip -r9 ../kernel-ksu.zip .
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: kernel-ksu-ak3
        path: kernel-ksu.zip
